import HSStaticMethods from 'preline';
import { icon, ring } from './icons.js';
import { escapeHtml as e, removable, plan, summarize, categories, validBaseUrl, taskLabel, recoverableApps } from './model.js';
import { native, hasNative, api } from './bridge.js';
const main = document.querySelector('#main');
const assist = document.body.dataset.surface === 'assist' || location.pathname.startsWith('/assist');
let route = 'home', busy = false, error = '', selected = new Set(), search = '', filter = 'removable';
let state = { inventory: [], scannedAt: null, vpn:{active:false,blockedCount:0}, capabilities:{shizuku:false},history:[],remote:null,serverUrl:'' };
let guest = null, guestState = null, pollTimer = null, nativePolling = false;
const featureItems = [['clean','清理软件','clean'],['block','广告防护','ads'],['family','请家人帮忙','remote'],['bell','通知管理','notifications'],['lock','安全权限','permissions'],['history','处理记录','history']];
function announce(text) {document.querySelector('#live').textContent = text;}
function notice(text,kind='') {return `<div class="notice ${kind}" role="${kind==='error'?'alert':'note'}">${text}</div>`;}
function header(title, back=true) {return `<header class="topbar"><div class="heading">${back?`<button class="icon-button" data-action="home" aria-label="返回首页">${icon('back')}</button>`:`<span class="brand-icon">${icon('shield',25)}</span>`}<div><h1>${e(title)}</h1>${!back?'<p class="brand-subtitle">简单整理，常用软件保留</p>':''}</div></div>${!back?`<button class="icon-button" data-action="manage" aria-label="打开设置">${icon('settings')}</button>`:''}</header>`;}
function button(text,action,kind='primary',disabled=false) {return `<button class="${kind} py-3 px-4 inline-flex items-center gap-x-2 rounded-xl font-semibold focus:outline-none focus:ring-2 focus:ring-blue-500 disabled:pointer-events-none" data-action="${action}" ${disabled?'disabled':''}>${text}</button>`;}
function errorBlock() {return error ? notice(e(error),'error'):'';}
function changeRoute(next) {route=next;error='';render();main.focus();window.scrollTo(0,0);}
function restorePanel(compact=false){
 const items=Array.isArray(state.removedApps)?state.removedApps:[],available=recoverableApps(items),progress=state.restoreProgress||{},restoring=progress.running===true;
 return `<section class="removal-panel rounded-2xl border border-gray-200 bg-white" aria-labelledby="removed-heading"><div class="panel-heading"><div><h2 id="removed-heading">已清理的软件 <span class="count-badge">${items.length}</span></h2><p>看得见处理结果，也能恢复安装</p></div>${compact&&items.length?`<button class="text-button" data-action="history">查看全部</button>`:''}</div>${restoring?`<div class="restore-progress" role="status">正在恢复 ${Number(progress.completed)||0} / ${Number(progress.total)||0} 项${progress.failed?'，'+e(progress.failed)+'项未完成':''}</div>`:''}${items.length?`<div class="removed-list">${(compact?items.slice(0,3):items).map(item=>`<div class="removed-row"><span class="app-tile">${icon('app',23)}</span><div class="row-main"><span class="row-title">${e(item.label||item.packageName)}</span><span class="row-detail">${item.restorable&&item.backupAvailable?'安装包已备份 · 可以恢复':e(item.reason||'安装包备份不可用')}</span></div>${!compact&&item.restorable&&item.backupAvailable?`<button class="row-action" data-action="restore" data-package="${e(item.packageName)}" ${restoring||busy?'disabled':''}>恢复</button>`:''}</div>`).join('')}</div>${available.length?button(restoring?'正在恢复…':'一键恢复'+(available.length>1?' '+available.length+' 项':''),'restore-all','secondary restore-all-button',restoring||busy||!hasNative()):''}`:'<div class="empty-removed">还没有已清理的软件。处理后会在这里留下记录。</div>'}<p class="restore-note">恢复软件不等于恢复原来的聊天记录和账号数据。</p></section>`;
}
function home() {
 const working=busy||state.cleaning||state.optimizing,last=state.lastOptimization,vpn=state.vpn||{},restoring=state.restoreProgress&&state.restoreProgress.running;
 const title=working?'正在整理':last?(last.failed?'检查完成':'整理完成'):'准备就绪';
 const caption=working?'请稍等，完成后会显示结果':'按常用软件名单保留，其余安全处理';
 return `${header('安心手机',false)}${!hasNative()?notice('网页界面预览，真实手机操作未连接。'):''}${errorBlock()}<section class="optimization-panel rounded-2xl bg-white border border-gray-200"><div class="panel-caption"><span class="status-pill">${state.prepared?'已完成初始化':'等待首次配置'}</span><span>日常只需点一下</span></div><div class="status-circle">${ring()}<div class="circle-content"><span class="big">${title}</span><span class="circle-caption">${working?'正在处理，请不要重复点击':'常用软件按名单保留'}</span></div></div>${button(working?'正在优化…':'一键优化','optimize','primary home-primary',working||restoring||!hasNative())}<div class="quiet-status"><span class="status-symbol ${vpn.active?'is-active':''}">${icon(vpn.active?'shield':'info',19)}</span><span>${vpn.starting?'广告防护正在开启':vpn.active?'广告防护已开启':vpn.lastError?'广告防护暂未运行':'广告防护未开启'}</span></div>${last?`<p class="optimization-result" role="status">${e(last.summary)}</p>`:''}</section>${restorePanel(true)}<footer class="simple-footer"><button class="footer-link" data-action="history">${icon('history',20)}清理记录</button><button class="footer-link" data-action="manage">${icon('settings',20)}设置</button></footer>`;
}
function manage(){
 return `${header('设置')}<p class="section-intro">日常只需“一键优化”。常用软件和更新在这里调整。</p><section class="settings-group rounded-2xl border border-gray-200 bg-white">${[['whitelist','常用软件名单','名单里的软件不会被清理。','shield'],['updates','软件更新','在手机上检查和安装新版本。','history']].map(([action,title,detail,i])=>`<button class="setting-link" data-action="${action}"><span class="setting-icon">${icon(i,23)}</span><span class="row-main"><span class="row-title">${title}</span><span class="row-detail">${detail}</span></span>${icon('arrow',18)}</button>`).join('')}</section><div class="hs-accordion-group"><div class="hs-accordion" id="advanced-settings"><button class="hs-accordion-toggle setting-disclosure" aria-controls="advanced-settings-content" aria-expanded="false">更多帮助 ${icon('arrow',18)}</button><div id="advanced-settings-content" class="hs-accordion-content hidden" role="region" aria-labelledby="advanced-settings"><section class="settings-group">${[['ads','广告防护','自动更新规则，偶尔查看即可。'],['remote','请家人帮忙','自己处理不了时，再邀请家人。'],['settings','连接设置','电脑自动配置的协助地址。'],['permissions','安全权限','需要排查时才查看。'],['about','隐私与能力说明','查看工具的范围和限制。']].map(([action,title,detail])=>`<button class="setting-link" data-action="${action}"><span class="row-main"><span class="row-title">${title}</span><span class="row-detail">${detail}</span></span>${icon('arrow',18)}</button>`).join('')}</section></div></div></div>`;
}
function updates(){
 const update=state.update||{};
 return `${header('软件更新')}<section class="removal-panel"><h2>安心手机</h2><p class="section-intro">当前版本 ${e(update.currentVersion||'0.4.0')}</p>${errorBlock()}${update.error?notice(e(update.error),'warning'):''}${update.latestVersion?`<p class="row-title">${update.available?'可更新至 '+e(update.latestVersion):'已经是最新版本'}</p>`:''}${button(busy?'正在检查…':'检查更新','check-update','secondary',busy||!hasNative())}${update.available?`<div class="bottom-actions">${button('下载并安装更新','install-update','primary',busy||!hasNative())}</div>`:''}<p class="disclaimer">从本项目GitHub发布获取安装包，下载后检查完整性、软件身份和签名。安装时按系统提示确认，不清除现有数据。</p><button class="text-button" data-action="open-release">GitHub发布页面</button></section>`;
}
function whitelist(){
 const items=state.whitelist||[];
 return `${header('常用软件名单')}<p class="section-intro">勾选“保留”的软件，不会进入清理名单。修改后点下面的“保存名单”。</p>${errorBlock()}<section class="settings-group whitelist-group rounded-2xl border border-gray-200 bg-white">${items.length?items.map(item=>`<label class="whitelist-row"><span class="app-tile">${icon('app',22)}</span><span class="row-main"><strong>${e(item.label)}</strong>${!item.installed?'<span class="hint">以后安装也会保留</span>':''}</span><span class="keep-control"><input type="checkbox" data-keep="${e(item.packageName)}" ${item.kept?'checked':''}><span>保留</span></span></label>`).join(''):'<p class="empty">名单尚未加载，请返回首页后重试。</p>'}</section><div class="bottom-actions">${button('保存名单','save-whitelist','primary',!hasNative()||busy)}</div><p class="disclaimer">电话、输入法等核心功能始终保护，不受这个名单影响。</p>`;
}
function appRows(items, context='phone') {
 const query=search.trim().toLowerCase();
 const matches=items.filter(x=>(filter==='all'||removable(x))&&(!query||(x.label+' '+x.packageName).toLowerCase().includes(query)));
 if(!matches.length)return '<div class="empty">没有符合条件的软件。<br>可以切换“全部软件”查看保护名单。</div>';
 return `<div class="app-list">${matches.map(x=>`<div class="app-row">${removable(x)?`<input type="checkbox" id="pkg-${e(x.packageName)}" data-package="${e(x.packageName)}" ${selected.has(x.packageName)?'checked':''} aria-label="选择${e(x.label)}">`:`<span class="protected-mark">${icon('shield',24)}</span>`}<label for="pkg-${e(x.packageName)}"><span class="app-name">${e(x.label)}</span><div class="package-name">${e(x.packageName)}</div><span class="tag ${e(x.category)}">${e(categories[x.category]||'需要核对')}${x.reason?' · '+e(x.reason):''}</span></label></div>`).join('')}</div>`;
}
function clean() {
 const sums=summarize(state.inventory);
 return `${header('清理软件')}<p class="section-intro">先保住电话、输入法和系统功能。其余软件由你决定是否清理。</p>${!hasNative()?notice('网页预览没有连接手机，不能读取或删除应用。'):''}${errorBlock()}${!state.scannedAt?`${button('先检查手机','scan','primary',!hasNative()||busy)}<div class="empty">检查后显示可清理的软件。<br>不会自动删除任何应用。</div>`:`<div class="summary-line"><span>可清理 ${sums.removable} 项</span><span>保护 ${sums.core} 项</span><span>待核对 ${sums.unknown} 项</span></div><div class="toolbar">${button('可清理软件','filter-removable','secondary')}${button('全部软件','filter-all','secondary')}${button('全选可清理','select-all','secondary')}</div><label class="field"><span class="sr-only">查找软件名称</span><input data-input="search" type="search" value="${e(search)}" placeholder="查找软件名称"></label>${appRows(state.inventory)}<div class="bottom-actions">${button('清理选中 '+selected.size+' 项','clean-confirm','primary',!selected.size||busy)}</div><p class="disclaimer">先备份安装包，再执行卸载。安装包备份不包含聊天、照片或应用私有数据。未确认依赖的系统包暂不处理。</p>`}`;
}
function ads() {
 const vpn=state.vpn||{},rule=state.ruleUpdate||{};
 return `${header('广告防护')}<p class="section-intro">广告防护由初始化自动开启，不需要日常调整。</p>${errorBlock()}<div class="session-state"><span class="dot ${vpn.active?'active':''}"></span>${vpn.active?'广告防护已开启':'广告防护未开启'}</div>${vpn.active?`<p class="section-intro">已拦截 ${Number(vpn.blockedCount)||0} 次广告域名请求。</p>`:''}${vpn.lastError?`<details class="technical-details"><summary>查看诊断信息</summary><p>${e(vpn.lastError)}</p></details>`:''}<div class="rule-update-status"><strong>广告规则自动更新</strong><p>来源：GitHub StevenBlack/hosts</p><p>${rule.count?'已缓存 '+e(rule.count)+' 条规则':'联网后自动获取拦截列表'}${rule.lastSuccess?' · '+e(new Date(rule.lastSuccess).toLocaleDateString('zh-CN')):''}</p>${rule.error?`<p class="hint">更新暂未完成，继续使用已有规则。</p>`:''}${button(rule.updating?'正在更新…':'立即更新规则','rules-update','secondary',busy||rule.updating||!hasNative())}</div>${state.rulesPendingRestart?notice('规则已保存。正在开启的过滤仍使用旧规则，关闭并重新开启广告防护后生效。'):''}${button(vpn.active?'关闭广告防护':'开启广告防护',vpn.active?'vpn-stop':'vpn-start','primary',!hasNative()||busy)}<div class="row"><div class="row-main"><span class="row-title">推广通知</span><span class="row-detail">关掉不需要的应用通知，保留重要消息。</span></div><button class="row-action" data-action="notifications">管理</button></div><div class="row"><div class="row-main"><span class="row-title">悬浮广告</span><span class="row-detail">检查哪些软件能覆盖其他应用显示。</span></div><button class="row-action" data-action="overlay-settings">检查</button></div><div class="row"><div class="row-main"><span class="row-title">广告域名规则</span><span class="row-detail">误拦时可以加入允许名单。</span></div><button class="row-action" data-action="rules">管理</button></div>${notice('<strong>防护范围</strong>仅过滤系统经本地虚拟 DNS 发出的 IPv4/UDP DNS 请求。不解密 HTTPS，不能过滤同域广告、已缓存广告、应用自带加密 DNS 或所有应用内弹窗；不接管普通网络流量。')}<p class="disclaimer">本地过滤需要 VPN 授权。已有 VPN 使用中时不会替换它。重启或授权被撤销后需重新开启。</p>`;
}
function remote() {
 const r=state.remote;
 return `${header('请家人帮忙')}<p class="section-intro">先发邀请，确认是你的家人后再允许查看和清理。你随时可以断开。</p>${errorBlock()}${state.remoteError?notice(e(state.remoteError),'error'):''}${!state.serverUrl?`${notice('需要先由子女设置远程协助服务地址。不能把手机 ADB 直接开放到公网。')}${button('设置服务地址','settings','primary',!hasNative())}`:!r?`${button('生成协助邀请','remote-create','primary',!hasNative()||busy)}<p class="disclaimer">邀请最多30分钟，仅能被领取一次。领取邀请不等于获得清理权限。</p>`:`<div class="session-state"><span class="dot ${r.phase==='approved'?'active':''}"></span>${r.phase==='approved'?'家人协助中':r.phase==='claimed'?'等待你确认家人':'等待家人领取'}</div><p>截止时间：${e(new Date(r.expiresAt).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'}))}</p>${r.inviteUrl&&r.phase!=='claimed'&&r.phase!=='approved'?`<div class="session-link">${e(r.inviteUrl)}</div>${button('分享邀请链接','remote-share','secondary')}`:''}${r.phase==='claimed'?`${notice('<strong>'+e(r.childName||'家人')+' 请求协助</strong>只有你点允许后，对方才能查看应用清单。')}${button('允许这位家人协助','remote-approve')}`:''}${r.phase==='approved'?notice('请保持安心手机打开。家人提交清理名单后，还会在这台手机上请你确认。'):''}<div class="bottom-actions">${button('立即断开协助','remote-revoke','danger',busy)}</div>`}<p class="disclaimer">远程端只提供清理任务，不提供短信读取、私人文件浏览或任意命令。</p>`;
}
function notifications() {return `${header('通知管理')}<p class="section-intro">关闭推广通知，不影响你想保留的重要消息。</p>${errorBlock()}${button('打开系统通知设置','notification-settings','primary',!hasNative())}<p class="disclaimer">在系统页面中选择经常发广告的软件，再关闭对应通知。普通手机助手不能静默撤销其他软件的通知权限。</p>`;}
function permissions() {return `${header('安全权限')}<p class="section-intro">重点检查陌生软件获得的高风险授权。不能只凭这些权限判断软件有毒。</p>${errorBlock()}${[['overlay-settings','悬浮窗权限','用于覆盖其他应用显示，也可能被用于弹出广告。'],['unknown-sources','安装未知应用','检查浏览器、下载工具等是否被允许安装软件。'],['accessibility-settings','无障碍服务','只保留明确需要且信任的服务。'],['admin-settings','设备管理应用','陌生管理应用可能阻止正常卸载。']].map(([a,t,d])=>`<div class="row"><div class="row-main"><span class="row-title">${t}</span><span class="row-detail">${d}</span></div><button class="row-action" data-action="${a}" ${!hasNative()?'disabled':''}>检查</button></div>`).join('')}${notice('不关闭系统更新和安全服务。不自动打开无障碍、不安装 HTTPS 解密证书，也不承诺“永不中毒”。')}`;}
function history() {
 return `${header('清理与恢复')}<p class="section-intro">每次处理都留下实际结果，恢复后会从待恢复名单移除。</p>${errorBlock()}${restorePanel()}<h2 class="section-title">处理记录</h2><section class="timeline-list">${!state.history.length?'<p class="empty">还没有处理记录。</p>':state.history.slice().reverse().map(item=>`<div class="result-item"><span class="timeline-icon">${icon(item.action==='restore'?'history':'clean',20)}</span><div class="row-main"><div class="row-title">${e(item.label||item.packageName)}</div><div class="result-status"><span class="result-badge ${item.status==='succeeded'?'success':'warning'}">${item.action==='restore'?'恢复':'清理'}${item.status==='succeeded'?'完成':item.status==='failed'?'未完成':item.status==='rejected'?'已取消':'处理中'}</span></div><p class="row-detail">${e(item.message)}</p><div class="history-time">${e(new Date(item.time).toLocaleString('zh-CN'))}</div></div></div>`).join('')}</section>`;
}
function settings() {return `${header('设置')}<div class="stack"><label class="field"><span>远程协助服务地址</span><input id="server-url" type="url" value="${e(state.serverUrl)}" placeholder="https://你的协助服务地址" autocapitalize="none" spellcheck="false"><span class="hint">由子女配置自己的 HTTPS 服务。未配置也能使用本地清理和广告防护。</span></label>${errorBlock()}${button('保存服务地址','save-server','primary',!hasNative())}<div class="row"><div class="row-main"><span class="row-title">高级清理授权</span><span class="row-detail">${state.capabilities.shizuku?'清理助手已连接，无需额外操作。':'尚未初始化，请连接电脑完成一次配置。'}</span></div></div>${button('查看初始化说明','shizuku','secondary',!hasNative())}<p class="hint">电脑初始化后即可使用。手机重启后，ADB辅助通道可能需要再次连接电脑恢复；不修改系统分区。</p>${button('查看隐私与能力说明','about','secondary')}</div>`;}
function rules() {return `${header('广告域名规则')}<p class="section-intro">每行一个域名，同时匹配其子域名。不填网址、通配符或 IP 地址。</p><div class="stack"><label class="field"><span>拦截域名</span><textarea id="blocked-domains" spellcheck="false" autocapitalize="none">${e((state.blockedDomains||[]).join('\n'))}</textarea></label><label class="field"><span>允许域名（优先）</span><textarea id="allowed-domains" spellcheck="false" autocapitalize="none">${e((state.allowedDomains||[]).join('\n'))}</textarea><span class="hint">登录、支付等被误拦时，可加入明确需要的域名。</span></label>${errorBlock()}${state.rulesPendingRestart?notice('规则已保存。正在开启的过滤仍使用旧规则，关闭并重新开启广告防护后生效。'):''}${button('保存规则','save-rules','primary',!hasNative())}</div>`;}
function about(){return `${header('能力与隐私')}<div class="stack"><p>本工具不含广告、第三方分析或病毒扫描引擎。不捏造安全分数，不保证清理后手机绝无风险。</p><p>核心组件强制保护。未知系统包等待核对。预装应用默认只做用户级移除，系统镜像里的 APK 仍保留。</p><p>安装包备份、清理记录和域名规则保存在手机本地。远程协助仅在主动发起、批准后分享应用清单；临时会话过期失效。</p><p>域名过滤仅计数，不上传完整浏览记录。服务端不保留永久家庭账号；重启会使现有协助会话失效。</p><p>手机端：Android 9及以上。源码和开源借鉴说明随项目提供。</p></div>`;}
function render(){if(assist){renderAssist();return;}main.className=busy?'working':'';const fn={home,manage,updates,whitelist,clean,ads,remote,notifications,permissions,history,settings,rules,about}[route]||home;main.innerHTML=`<div class="phone ${route==='home'?'home-screen':''}">${fn()}</div>`;HSStaticMethods.autoInit(['accordion']);}
async function run(action,data={},message){if(busy)return;busy=true;error='';render();try{const result=await native(action,data);if(result&&result.state)state=result.state;else state=await native('getState');if(message)announce(message);}catch(x){error=x.message;announce(error);}finally{busy=false;render();}}
async function dialog({title,html,confirm='确认',danger=false,check=false,onConfirm,onCancel}) {
 const root=document.querySelector('#dialog-root'),previous=document.activeElement;
 root.innerHTML=`<div class="dialog-backdrop"><section class="dialog" role="dialog" aria-modal="true" aria-labelledby="dialog-title"><h2 id="dialog-title">${e(title)}</h2>${html}${check?'<label class="checkline"><input id="acknowledge" type="checkbox"><span>我知道：目标应用的数据可能永久丢失，安装包备份不能恢复聊天和账号数据。</span></label>':''}<div class="dialog-actions"><button class="secondary" id="dialog-cancel">取消</button><button class="${danger?'danger':'primary'}" id="dialog-confirm" ${check?'disabled':''}>${e(confirm)}</button></div></section></div>`;
 const close=()=>{root.innerHTML='';root.onkeydown=null;if(previous&&previous.isConnected)previous.focus();};
 const decline=()=>{close();if(onCancel)onCancel();};
 document.querySelector('#dialog-cancel').onclick=decline;
 if(check)document.querySelector('#acknowledge').onchange=x=>{document.querySelector('#dialog-confirm').disabled=!x.target.checked;};
 document.querySelector('#dialog-confirm').onclick=async()=>{close();await onConfirm();};
 root.onkeydown=x=>{if(x.key==='Escape'){decline();return;}if(x.key==='Tab'){const nodes=[...root.querySelectorAll('button:not(:disabled),input')];const first=nodes[0],last=nodes[nodes.length-1];if(x.shiftKey&&document.activeElement===first){x.preventDefault();last.focus();}else if(!x.shiftKey&&document.activeElement===last){x.preventDefault();first.focus();}}};
 document.querySelector('#dialog-cancel').focus();
}
async function confirmClean(){let targets;try{targets=plan(state.inventory,[...selected]);}catch(x){error=x.message;render();return;}await dialog({title:'清理这 '+targets.length+' 个软件？',html:`<p>核心组件不会删除。请确认这些软件不再需要。</p><ul class="plain-list">${targets.map(x=>'<li>'+e(x.label)+'</li>').join('')}</ul>`,confirm:'备份并清理',danger:true,check:true,onConfirm:()=>run('uninstall',{packages:targets.map(x=>x.packageName),acknowledgeDataLoss:true},'清理任务已交给手机。')});}
main.addEventListener('change',x=>{if(x.target.dataset.package){if(x.target.checked)selected.add(x.target.dataset.package);else selected.delete(x.target.dataset.package);const button=main.querySelector('[data-action="clean-confirm"],[data-action="guest-clean"]');if(button){button.textContent='清理选中 '+selected.size+' 项';button.disabled=!selected.size||busy;}}});
main.addEventListener('input',x=>{if(x.target.dataset.input==='search'){search=x.target.value;const list=main.querySelector('.app-list,.empty');if(list){const wrap=document.createElement('div');wrap.innerHTML=appRows(assist&&guestState?guestState.inventory:state.inventory);list.replaceWith(wrap.firstElementChild);}}});
main.addEventListener('click',async x=>{
 const target=x.target.closest('[data-action]');if(!target||target.disabled)return;const a=target.dataset.action;
 if(assist){await assistAction(a);return;}
 if(['home','manage','updates','whitelist','clean','ads','remote','notifications','permissions','history','settings','rules','about'].includes(a)){changeRoute(a);return;}
 if(a==='open-release'){if(hasNative())await run('open-release');else window.open('https://github.com/zzusec/anshin-phone/releases','_blank','noopener,noreferrer');return;}
 if(a==='check-update'){await run('update:check',{},'更新检查完成。');return;}
 if(a==='install-update'){await run('update:install',{},'下载校验完成，请按系统提示安装。');return;}
 if(a==='rules-update'){await run('rules:update',{},'广告规则更新完成。');return;}
 if(a==='optimize'){await run('optimize',{},'手机整理已开始。');return;}
 if(a==='save-whitelist'){const packages=[...main.querySelectorAll('[data-keep]:checked')].map(input=>input.dataset.keep);await run('whitelist:save',{packages},'常用软件名单已保存。');return;}
 if(a==='scan'){await run('scan',{},'手机检查完成。');selected=new Set(state.inventory.filter(removable).map(x=>x.packageName));render();return;}
 if(a==='filter-removable'||a==='filter-all'){filter=a==='filter-all'?'all':'removable';render();return;}
 if(a==='select-all'){selected=new Set(state.inventory.filter(removable).map(x=>x.packageName));render();return;}
 if(a==='clean-confirm'){await confirmClean();return;}
 if(a==='vpn-start'){await dialog({title:'开启广告防护？',html:'<p>手机会弹出系统 VPN 授权。已有 VPN 使用中时不会替换它。此功能不是病毒扫描，也不能过滤所有广告。</p>',confirm:'继续授权',onConfirm:()=>run('vpn',{enabled:true})});return;}
 if(a==='vpn-stop'){await run('vpn',{enabled:false});return;}
 if(a==='save-server'){try{const base=validBaseUrl(document.querySelector('#server-url').value.trim());await run('config:save',{serverUrl:base},'服务地址已保存。');}catch(x){error=x.message;render();}return;}
 if(a==='save-rules'){await run('rules:save',{blockedDomains:document.querySelector('#blocked-domains').value.split('\n').filter(x=>x.trim()),allowedDomains:document.querySelector('#allowed-domains').value.split('\n').filter(x=>x.trim())},'域名规则已保存。');return;}
 if(a==='remote-create'){await run('remote:create');return;}
 if(a==='remote-approve'){await run('remote:approve');return;}
 if(a==='remote-revoke'){await run('remote:revoke');return;}
 if(a==='remote-share'){await run('share',{text:state.remote.inviteUrl});return;}
 if(a==='restore'||a==='restore-all'){const name=target.dataset.package;const apps=a==='restore'?recoverableApps(state.removedApps||[]).filter(item=>item.packageName===name):recoverableApps(state.removedApps||[]);await dialog({title:a==='restore'?'恢复这个软件？':'恢复 '+apps.length+' 个软件？',html:'<p>只恢复软件安装。卸载前的聊天记录和账号数据不保证找回。</p><ul class="plain-list">'+apps.map(item=>'<li>'+e(item.label||item.packageName)+'</li>').join('')+'</ul>',confirm:'开始恢复',onConfirm:()=>run(a==='restore'?'restore':'restore-all',a==='restore'?{packageName:name}:{},'恢复任务已开始。')});return;}
 if(a==='shizuku'){await run('shizuku');return;}
 if(['notification-settings','overlay-settings','unknown-sources','accessibility-settings','admin-settings'].includes(a)){await run('settings',{screen:a});return;}
});
function renderAssist(){
 if(!guest){main.innerHTML=`<div class="assist-shell"><header class="topbar"><div class="assist-title">${icon('shield',28)}<h1>安心手机 · 家人协助</h1></div></header><section class="assist-login"><h1>帮家人整理手机</h1><p class="section-intro">领取邀请后，请家人在手机上确认你的身份。批准前不能查看应用或提交清理。</p><label class="field"><span>你的称呼</span><input id="child-name" maxlength="32" autocomplete="nickname" placeholder="例如：女儿小林"></label>${errorBlock()}${button(busy?'正在领取…':'领取协助邀请','guest-claim','primary',busy)}<p class="disclaimer">邀请只能领取一次，最多30分钟。不要转发给陌生人。</p></section></div>`;return;}
 const s=guestState||{phase:'claimed'},approved=s.phase==='approved';
 main.innerHTML=`<div class="assist-shell"><header class="topbar"><div class="assist-title">${icon('shield',28)}<h1>家人协助</h1></div><span class="subline">仅限本次授权</span></header><div class="assist-layout"><aside class="assist-side"><h2>${approved?'协助已获批准':'等待手机确认'}</h2><div class="session-state"><span class="dot ${approved&&s.deviceOnline?'active':''}"></span>${approved?(s.deviceOnline?'手机已连接':'手机暂未响应'):'尚未获准访问'}</div><p class="hint">${approved?'请家人保持手机助手打开。清理名单还需在手机上确认。':'请家人在安心手机里点“允许这位家人协助”。批准前不会显示任何应用信息。'}</p><p class="disclaimer">${s.expiresAt?'截至 '+e(new Date(s.expiresAt).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})):''}</p>${button('退出此页面','guest-leave','secondary')}<p class="disclaimer">退出页面不等于撤销授权；请在老人手机上点“立即断开协助”撤销会话。</p></aside><section class="assist-content">${errorBlock()}${approved?`<h2>选择要清理的软件</h2><p class="section-intro">系统核心组件不可选。清理会删除目标应用的数据。</p><div class="toolbar">${button('可清理软件','filter-removable','secondary')}${button('全部软件','filter-all','secondary')}${button('全选可清理','guest-select-all','secondary')}</div>${appRows(s.inventory||[],'guest')}<div class="bottom-actions">${button('清理选中 '+selected.size+' 项','guest-clean','primary',!selected.size||busy||!s.deviceOnline)}</div><h2>任务进度</h2>${(s.commands||[]).length?s.commands.slice().reverse().map(c=>`<div class="result-item"><div class="row-title">${c.packages.length} 项清理 · ${e(taskLabel(c.status))}</div>${(c.results||[]).map(r=>`<p class="hint">${e(r.packageName)}：${e(r.message)}</p>`).join('')}</div>`).join(''):'<p class="hint">还没有提交任务。</p>'}`:`<div class="empty">${icon('lock',44)}<p>家人确认后，应用清单才会显示。</p></div>`}</section></div></div>`;
}
async function assistAction(a){
 if(a==='guest-claim'){
  const childName=document.querySelector('#child-name').value.trim();if(!childName){error='请填写家人能认出的称呼。';render();return;}
  const inviteToken=new URLSearchParams(location.hash.slice(1)).get('invite');if(!inviteToken){error='邀请链接不完整，请家人重新分享链接。';render();return;}
  busy=true;error='';render();try{guest=await api('/api/claim',null,{inviteToken,childName});historyReplace();await pollGuest();pollTimer=setInterval(pollGuest,3000);}catch(x){error=x.message;}finally{busy=false;render();}return;
 }
 if(a==='guest-leave'){clearInterval(pollTimer);guest=null;guestState=null;selected.clear();error='邀请已经领取。如需重新连接，请在手机上重新发起邀请。';render();return;}
 if(a==='filter-removable'||a==='filter-all'){filter=a==='filter-all'?'all':'removable';render();return;}
 if(a==='guest-select-all'){selected=new Set((guestState.inventory||[]).filter(removable).map(x=>x.packageName));render();return;}
 if(a==='guest-clean'){
  let targets;try{targets=plan(guestState.inventory,[...selected]);}catch(x){error=x.message;render();return;}
  await dialog({title:'提交 '+targets.length+' 项清理？',html:`<p>手机还会请持有人确认本次名单。不会处理核心组件。</p><ul class="plain-list">${targets.map(x=>'<li>'+e(x.label)+'</li>').join('')}</ul>`,confirm:'提交给手机确认',danger:true,check:true,onConfirm:async()=>{busy=true;error='';render();try{await api('/api/sessions/'+guest.sessionId+'/commands',guest.guestToken,{action:'uninstall',packages:targets.map(x=>x.packageName),acknowledgeDataLoss:true});selected.clear();await pollGuest();announce('清理名单已提交，等待手机确认。');}catch(x){error=x.message;}finally{busy=false;render();}}});
 }
}
function historyReplace(){window.history.replaceState(null,'',location.pathname);}
let guestPolling=false;
async function pollGuest(){if(!guest||guestPolling)return;guestPolling=true;try{guestState=await api('/api/sessions/'+guest.sessionId+'/guest',guest.guestToken);error='';render();}catch(x){error=x.message;clearInterval(pollTimer);render();}finally{guestPolling=false;}}
let taskDialogReject=null;
window.addEventListener('native-remote-task',event=>{
 const task=event.detail;
 // 取消按钮、Escape、返回导航都必须给出明确拒绝回报，不能让任务永远停在等待确认。
 const reject=()=>{if(!taskDialogReject)return;taskDialogReject=null;run('remote:execute',{commandId:task.id,approved:false});};
 taskDialogReject=reject;
 dialog({title:'家人请求清理 '+task.apps.length+' 个软件',html:`<p>仅处理下面的名单。你可以拒绝。</p><ul class="plain-list">${task.apps.map(x=>'<li>'+e(x.label)+'</li>').join('')}</ul>`,confirm:'允许本次清理',danger:true,check:true,
  onCancel:reject,
  onConfirm:()=>{taskDialogReject=null;return run('remote:execute',{commandId:task.id,approved:true});}});
});
window.addEventListener('native-navigate',event=>{if(taskDialogReject)taskDialogReject();changeRoute(event.detail.route||'home');});
render();
if(!assist&&hasNative()){
 native('getState').then(x=>{state=x;render();}).catch(x=>{error=x.message;render();});
 setInterval(async()=>{if(nativePolling||busy||document.hidden||document.querySelector('.dialog'))return;nativePolling=true;try{state=await native('getState');if(['home','ads','remote','history'].includes(route))render();}catch(x){error=x.message;if(route==='remote')render();}finally{nativePolling=false;}},5000);
}
